name: Docker Image Call CI

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      app_name:
        description: 'app_name'
        required: true
        default: 'wechat-bot'
        type: string
      app_version:
        description: 'app_version'
        required: true
        type: string
        default: '1.0'


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: image Build and push
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}"
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.app_name }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.app_name }}:${{ inputs.app_version }}
